"""Compare Logistic Regression against Random Forest on the Fire Detection V1 dataset.

Reuses the existing training_v1.csv unchanged (does not regenerate it) and
the existing Logistic Regression Pipeline configuration from
scripts.train_fire_detection_model - it is refit here only so its held-out
and cross-validation metrics can be measured on the exact same split/folds
as Random Forest; the already-saved fire_detection_logistic_v1.joblib is
never touched or overwritten. Random Forest is trained fresh and saved as a
separate artifact.

This is an offline comparison script only - it does not select a runtime
classifier and does not modify FireDetectionAgent or FireDetectionCalculator.
As an additional, optional analysis (Part 21), the same held-out rows are
also evaluated with the unmodified rule-based FireDetectionCalculator, using
evidence regenerated by FireDetectionTrainingDataGenerator (the CSV itself
only stores summarized features, not raw evidence) after confirming that
regeneration reproduces training_v1.csv exactly.

Example:
    python -m scripts.compare_fire_detection_models
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import joblib

from scripts.train_fire_detection_model import DEFAULT_DATASET_PATH, MAX_ITER, build_pipeline as build_logistic_pipeline
from src.ml.fire_detection.fire_detection_dataset import load_training_dataset_rows
from src.ml.fire_detection.fire_detection_features import FIRE_DETECTION_FEATURE_NAMES
from src.ml.fire_detection.fire_detection_model_comparison import (
    CV_RANDOM_STATE,
    CV_SPLITS,
    HELD_OUT_RANDOM_STATE,
    HELD_OUT_TEST_SIZE,
    RF_N_ESTIMATORS,
    RF_RANDOM_STATE,
    build_random_forest,
    compute_feature_importances,
    compute_permutation_importance,
    evaluate_cross_validation,
    evaluate_held_out,
    evaluate_predictions,
    evaluate_rule_based_calculator,
    make_cv_splitter,
    make_held_out_split,
    regenerated_samples_match_dataset,
)
from src.ml.fire_detection.fire_detection_training_data_generator import (
    DEFAULT_TRAINING_DATA_SEED,
    FireDetectionTrainingDataGenerator,
)

MODEL_DIR = Path(__file__).resolve().parents[1] / "models" / "fire_detection"
RF_MODEL_PATH = MODEL_DIR / "fire_detection_random_forest_v1.joblib"
RF_METADATA_PATH = MODEL_DIR / "fire_detection_random_forest_v1_metadata.json"
COMPARISON_JSON_PATH = MODEL_DIR / "fire_detection_model_comparison_v1.json"
COMPARISON_MARKDOWN_PATH = Path(__file__).resolve().parents[1] / "docs" / "fire_detection_model_comparison.md"

RF_MODEL_VERSION = "1.0"


def _dataset_summary(rows) -> dict:
    positive = sum(1 for row in rows if row.label == 1)
    return {
        "total_samples": len(rows),
        "positive_samples": positive,
        "negative_samples": len(rows) - positive,
    }


def run_comparison(dataset_path: Path) -> dict:
    rows = load_training_dataset_rows(dataset_path)
    features = [list(row.features) for row in rows]
    labels = [row.label for row in rows]

    split = make_held_out_split(features, labels)
    cv = make_cv_splitter()

    # --- Logistic Regression (same Pipeline config as scripts.train_fire_detection_model;
    #     refit here only for this comparison - the saved fire_detection_logistic_v1.joblib
    #     artifact from Task 1 is left untouched) ---
    logistic_pipeline = build_logistic_pipeline()
    logistic_pipeline.fit(split.x_train, split.y_train)
    logistic_held_out = evaluate_held_out(logistic_pipeline, split.x_test, split.y_test)
    logistic_cv = evaluate_cross_validation(build_logistic_pipeline(), features, labels, cv)

    # --- Random Forest ---
    random_forest = build_random_forest()
    random_forest.fit(split.x_train, split.y_train)
    rf_train_metrics = evaluate_predictions(random_forest, split.x_train, split.y_train)
    rf_held_out = evaluate_held_out(random_forest, split.x_test, split.y_test)
    rf_cv = evaluate_cross_validation(build_random_forest(), features, labels, cv)
    feature_importances = compute_feature_importances(random_forest)
    permutation_importances = compute_permutation_importance(random_forest, split.x_test, split.y_test)

    # --- Optional: rule-based FireDetectionCalculator on the same held-out rows (Part 21) ---
    rule_based_metrics = None
    rule_based_skipped_reason = None
    generated_samples = FireDetectionTrainingDataGenerator(seed=DEFAULT_TRAINING_DATA_SEED).generate(
        num_samples=len(rows)
    )
    if regenerated_samples_match_dataset(rows, generated_samples):
        rule_based_metrics = evaluate_rule_based_calculator(generated_samples, split.test_indices)
    else:
        rule_based_skipped_reason = (
            "FireDetectionTrainingDataGenerator(seed=42) no longer reproduces training_v1.csv exactly "
            "(the CSV is stale relative to current generator code) - skipped rather than compared on "
            "mismatched evidence."
        )

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(random_forest, RF_MODEL_PATH)

    rf_metadata = {
        "model_type": "RandomForestClassifier",
        "model_role": "nonlinear_ml_comparison_candidate",
        "model_version": RF_MODEL_VERSION,
        "dataset": dataset_path.name,
        "random_seed": RF_RANDOM_STATE,
        "held_out_test_size": HELD_OUT_TEST_SIZE,
        "held_out_split_random_state": HELD_OUT_RANDOM_STATE,
        "feature_names": list(FIRE_DETECTION_FEATURE_NAMES),
        "training_configuration": {
            "n_estimators": RF_N_ESTIMATORS,
            "random_state": RF_RANDOM_STATE,
            "class_weight": None,
            "note": "sklearn defaults otherwise (max_depth=None, min_samples_leaf=1) - no held-out-test-driven tuning applied",
        },
        **_dataset_summary(rows),
        "train_samples": len(split.y_train),
        "test_samples": len(split.y_test),
        "train_metrics": rf_train_metrics,
        "held_out_metrics": rf_held_out,
        "cross_validation": {
            "n_splits": CV_SPLITS,
            "random_state": CV_RANDOM_STATE,
            "metrics": rf_cv,
        },
        "feature_importances_impurity": {name: value for name, value in feature_importances},
        "permutation_importances_held_out_f1": {name: value for name, value in permutation_importances},
        "importance_note": (
            "Impurity-based feature_importances_ is biased toward high-cardinality/correlated features and is "
            "not a causal measure; permutation importance (held-out, scoring='f1') is reported alongside it for "
            "the same reason - the feature set has structural/statistical correlation (see fire_detection_ml.md)."
        ),
    }
    RF_METADATA_PATH.write_text(json.dumps(rf_metadata, indent=2) + "\n", encoding="utf-8")

    comparison = {
        "dataset": dataset_path.name,
        **_dataset_summary(rows),
        "held_out_split": {
            "test_size": HELD_OUT_TEST_SIZE,
            "random_state": HELD_OUT_RANDOM_STATE,
            "train_samples": len(split.y_train),
            "test_samples": len(split.y_test),
        },
        "cross_validation": {"n_splits": CV_SPLITS, "random_state": CV_RANDOM_STATE, "shuffle": True},
        "logistic_regression": {
            "config": {"scaler": "StandardScaler", "max_iter": MAX_ITER, "random_state": HELD_OUT_RANDOM_STATE},
            "held_out_metrics": logistic_held_out,
            "cross_validation_metrics": logistic_cv,
        },
        "random_forest": {
            "config": rf_metadata["training_configuration"],
            "train_metrics": rf_train_metrics,
            "held_out_metrics": rf_held_out,
            "cross_validation_metrics": rf_cv,
            "feature_importances_impurity": rf_metadata["feature_importances_impurity"],
            "permutation_importances_held_out_f1": rf_metadata["permutation_importances_held_out_f1"],
        },
        "rule_based_calculator": rule_based_metrics,
        "rule_based_calculator_skipped_reason": rule_based_skipped_reason,
        "note": (
            "Dataset is synthetic (Part V1 proof-of-concept). These metrics measure relative performance on the "
            "synthetic V1 distribution only and are not real-world operational wildfire-detection accuracy. No "
            "runtime classifier is selected by this comparison."
        ),
    }
    COMPARISON_JSON_PATH.write_text(json.dumps(comparison, indent=2) + "\n", encoding="utf-8")

    return {
        "rows": rows,
        "split": split,
        "logistic_held_out": logistic_held_out,
        "logistic_cv": logistic_cv,
        "rf_train_metrics": rf_train_metrics,
        "rf_held_out": rf_held_out,
        "rf_cv": rf_cv,
        "feature_importances": feature_importances,
        "permutation_importances": permutation_importances,
        "rule_based_metrics": rule_based_metrics,
        "rule_based_skipped_reason": rule_based_skipped_reason,
        "comparison": comparison,
    }


def _format_metric_row(name: str, logistic_value: str, rf_value: str) -> str:
    return f"{name:<16}{logistic_value:<25}{rf_value}"


def _print_report(result: dict) -> None:
    logistic_held_out = result["logistic_held_out"]
    rf_held_out = result["rf_held_out"]
    logistic_cv = result["logistic_cv"]
    rf_cv = result["rf_cv"]

    print("=== Held-Out Test Metrics ===")
    print(_format_metric_row("Metric", "Logistic Regression", "Random Forest"))
    print("-" * 60)
    for metric in ("accuracy", "precision", "recall", "f1", "roc_auc"):
        print(
            _format_metric_row(
                metric.capitalize() if metric != "roc_auc" else "ROC-AUC",
                f"{logistic_held_out[metric]:.4f}",
                f"{rf_held_out[metric]:.4f}",
            )
        )
    print(_format_metric_row("False Positives", str(logistic_held_out["false_positive"]), str(rf_held_out["false_positive"])))
    print(_format_metric_row("False Negatives", str(logistic_held_out["false_negative"]), str(rf_held_out["false_negative"])))

    print("\n=== 5-Fold Cross-Validation (mean +/- std) ===")
    print(_format_metric_row("Metric", "Logistic Regression", "Random Forest"))
    print("-" * 60)
    for metric in ("accuracy", "precision", "recall", "f1", "roc_auc"):
        lr_cell = f"{logistic_cv[metric]['mean']:.3f} +/- {logistic_cv[metric]['std']:.3f}"
        rf_cell = f"{rf_cv[metric]['mean']:.3f} +/- {rf_cv[metric]['std']:.3f}"
        print(_format_metric_row(metric.capitalize() if metric != "roc_auc" else "ROC-AUC", lr_cell, rf_cell))

    print("\n=== Random Forest overfitting check (train vs held-out test) ===")
    print(f"Train: accuracy={result['rf_train_metrics']['accuracy']:.4f}  f1={result['rf_train_metrics']['f1']:.4f}")
    print(f"Test:  accuracy={rf_held_out['accuracy']:.4f}  f1={rf_held_out['f1']:.4f}")

    print("\n=== Random Forest feature importances (impurity-based, descending) ===")
    for name, value in result["feature_importances"]:
        print(f"  {name:<28} {value:.4f}")

    print("\n=== Random Forest permutation importance (held-out test, scoring=f1) ===")
    for name, value in result["permutation_importances"]:
        print(f"  {name:<28} {value:+.4f}")

    if result["rule_based_metrics"] is not None:
        rule_based = result["rule_based_metrics"]
        print("\n=== Rule-based FireDetectionCalculator on the same held-out rows (Part 21, optional) ===")
        print(
            f"Accuracy={rule_based['accuracy']:.4f}  Precision={rule_based['precision']:.4f}  "
            f"Recall={rule_based['recall']:.4f}  F1={rule_based['f1']:.4f}"
        )
        if "roc_auc_using_rule_based_confidence_as_score" in rule_based:
            print(
                "ROC-AUC (using decision.confidence as score - a rule-based heuristic value, "
                f"not a calibrated probability): {rule_based['roc_auc_using_rule_based_confidence_as_score']:.4f}"
            )
        print(
            f"TN={rule_based['true_negative']}  FP={rule_based['false_positive']}  "
            f"FN={rule_based['false_negative']}  TP={rule_based['true_positive']}"
        )
    else:
        print(f"\nRule-based comparison skipped: {result['rule_based_skipped_reason']}")

    print(f"\nSaved Random Forest model: {RF_MODEL_PATH}")
    print(f"Saved Random Forest metadata: {RF_METADATA_PATH}")
    print(f"Saved comparison artifact: {COMPARISON_JSON_PATH}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare Logistic Regression vs Random Forest.")
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET_PATH)
    args = parser.parse_args()

    result = run_comparison(args.dataset)
    _print_report(result)


if __name__ == "__main__":
    main()
