"""The untouched confirmatory dataset for the Task 8 policy evaluation.

Generated by the FROZEN V5 generator (`FireDetectionTrainingDataGeneratorV5`, unchanged distributions, regimes,
pairs, label logic) with a NEW seed. The generator numbers environments / samples / pairs from 1 for every seed, so
each confirmatory row is namespaced by fixed offsets purely so that disjointness from training_v5.csv is checkable;
the environment PARAMETERS themselves are different because they are drawn from (seed, environment id).

This data never participates in training, model selection, feature selection, threshold selection or calibration.
"""
from __future__ import annotations

from collections import Counter
from dataclasses import replace
from pathlib import Path

from src.ml.fire_detection.fire_detection_dataset_v5 import (
    FireDetectionDatasetRowV5,
    dataset_sha256,
    load_training_dataset_rows_v5,
    write_training_dataset_v5,
)
from src.ml.fire_detection.fire_detection_policy_config_v5 import (
    CONFIRMATORY_ROWS,
    CONFIRMATORY_SEED,
    ENVIRONMENT_ID_OFFSET,
    PAIR_ID_OFFSET,
    SAMPLE_ID_OFFSET,
)
from src.ml.fire_detection.fire_detection_training_data_generator_v5 import (
    DEFAULT_TRAINING_DATA_SEED_V5,
    FireDetectionTrainingDataGeneratorV5,
    FireDetectionTrainingSampleV5,
)

DEFAULT_CONFIRMATORY_CSV = (
    Path(__file__).resolve().parents[3] / "data" / "fire_detection" / "fire_detection_v5_policy_validation.csv"
)


def generate_confirmatory_samples(
    seed: int = CONFIRMATORY_SEED, num_samples: int = CONFIRMATORY_ROWS
) -> tuple[FireDetectionTrainingSampleV5, ...]:
    """The frozen generator with a new seed, ids namespaced away from the training dataset."""
    if seed == DEFAULT_TRAINING_DATA_SEED_V5:
        raise ValueError("the confirmatory dataset must use a seed different from the V5 training seed.")
    samples = FireDetectionTrainingDataGeneratorV5(seed=seed).generate(num_samples)
    return tuple(
        replace(
            sample,
            sample_id=sample.sample_id + SAMPLE_ID_OFFSET,
            environment_id=sample.environment_id + ENVIRONMENT_ID_OFFSET,
            pair_id=None if sample.pair_id is None else sample.pair_id + PAIR_ID_OFFSET,
        )
        for sample in samples
    )


def write_confirmatory_dataset(path: Path = DEFAULT_CONFIRMATORY_CSV, seed: int = CONFIRMATORY_SEED) -> Path:
    return write_training_dataset_v5(generate_confirmatory_samples(seed), path)


def cross_dataset_overlap(
    training_rows: tuple[FireDetectionDatasetRowV5, ...],
    confirmatory_rows: tuple[FireDetectionDatasetRowV5, ...],
) -> dict:
    """Leakage checks between the training and confirmatory datasets (run BEFORE any evaluation).

    ids and seeds must not overlap. Exact feature-vector overlap is only a DIAGNOSTIC: low-dimensional (e.g. news-only)
    rows duplicate naturally, and nothing is removed after seeing results.
    """
    train_envs = {r.environment_id for r in training_rows}
    conf_envs = {r.environment_id for r in confirmatory_rows}
    train_samples = {r.sample_id for r in training_rows}
    conf_samples = {r.sample_id for r in confirmatory_rows}
    train_pairs = {r.pair_id for r in training_rows if r.pair_id is not None}
    conf_pairs = {r.pair_id for r in confirmatory_rows if r.pair_id is not None}
    train_vectors: dict[tuple, set[int]] = {}
    for r in training_rows:
        train_vectors.setdefault(r.features, set()).add(r.label)
    overlapping = [r for r in confirmatory_rows if r.features in train_vectors]
    by_regime = Counter(r.regime for r in overlapping)
    label_conflicts = sum(1 for r in overlapping if train_vectors[r.features] != {r.label})
    return {
        "training_seeds": sorted({r.seed for r in training_rows}),
        "confirmatory_seeds": sorted({r.seed for r in confirmatory_rows}),
        "shared_environment_ids": sorted(train_envs & conf_envs),
        "shared_sample_ids": sorted(train_samples & conf_samples),
        "shared_pair_ids": sorted(train_pairs & conf_pairs),
        "training_environments": len(train_envs),
        "confirmatory_environments": len(conf_envs),
        "confirmatory_pairs": len(conf_pairs),
        "exact_feature_vector_overlap_rows": len(overlapping),
        "exact_feature_vector_overlap_fraction": len(overlapping) / len(confirmatory_rows),
        "exact_overlap_by_regime": dict(sorted(by_regime.items())),
        "overlapping_rows_whose_vector_has_another_label_in_training": label_conflicts,
        "note": "exact-overlap is a diagnostic only (news-only rows duplicate by construction); no row is removed.",
    }


def assert_disjoint(overlap: dict) -> None:
    """Raise unless training and confirmatory data share no seed, environment, sample or pair id."""
    if set(overlap["training_seeds"]) & set(overlap["confirmatory_seeds"]):
        raise ValueError(f"confirmatory data shares a seed with training: {overlap['confirmatory_seeds']}")
    for key in ("shared_environment_ids", "shared_sample_ids", "shared_pair_ids"):
        if overlap[key]:
            raise ValueError(f"confirmatory data overlaps training: {key} has {len(overlap[key])} shared ids")


def confirmatory_sha256(path: Path = DEFAULT_CONFIRMATORY_CSV) -> str:
    return dataset_sha256(path)


def load_confirmatory_rows(path: Path = DEFAULT_CONFIRMATORY_CSV) -> tuple[FireDetectionDatasetRowV5, ...]:
    return load_training_dataset_rows_v5(path)
